all:
	g++ exercise.cpp -std=c++11 -o exercise
	g++ slowVersion.cpp -std=c++11 -o slowVersion
debug:
	g++ exercise.cpp -std=c++11 -o exercise -g
	g++ slowVersion.cpp -std=c++11 -o slowVersion -g
clean:
	rm exercise slowVersion