all:
	g++ exercise.cpp -std=c++11 -o exercise
	g++ reference.cpp -std=c++11 -o reference
debug:
	g++ exercise.cpp -std=c++11 -o exercise -g
	g++ reference.cpp -std=c++11 -o reference -g
clean:
	rm exercise reference